### ISSUE TITLE
Add loading animations to the hall of fame pages

### ISSUE THREAD

**Issue by CharanMN7** [devsForFun/devsForFun#34]
- [ ] Add a loading animation to the main hall of fame page.
- [ ] Add a loading animation to the hall of fame profile page.

**Comment by Nandan328** [comment]
I'd like to take this on. Could you please assign it to me?

**Comment by CharanMN7** [comment]
@Nandan328 Awesome! Thanks for helping out!

We are using Supabase for the data. You'll need access to that to see how the hall of fame pages are actually working. DM me your email address to me and I'll add you to the supabase organization. That will give you access to the necessary environment variables.

**Comment by CharanMN7** [comment]
Here's some notes on how to contribute with problems:
- Fork this repository to work on the issue (Pull/sync the latest changes to your fork before you start working)
- Once you're done with all the changes, run `npm run format` to sync the formatting with existing files. This helps avoid unnecessary changes.
- Run `npm run build` and fix any errors/warnings that stop the build process.
- Once you're done, make a pull request to the main branch of this repo from the main branch of the forked repo.
